
{'exp_name': 'pedsim_cpo', 'exp_epi_len': 200, 'pi_hidden_layers': [128, 128], 'pi_options': ['default', 'leaky-relu', 'default'], 'replay_size': 10000, 'gamma': 0.99, 'lambda': 0.97, 'polyak': 0.995, 'alpha': 0.002, 'learning_rate': 0.0001, 'epochs': 1000, 'steps_per_epoch': 100, 'batch_size': 256, 'n_log_epi': 10, 'start_steps': 100, 'update_after': 100, 'update_every': 20, 'save_interval': 10, 'plot_rendering': True, 'seed': 1}
/home/brain5/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
model_state:
  model_name: "goal"
  pose:
    position:
      x: 29.17600000000001
      y: 10.11334
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
model_state:
  model_name: "goal"
  pose:
    position:
      x: 14.710800000000013
      y: -0.9111199999999968
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
lidar collision
model_state:
  model_name: "goal"
  pose:
    position:
      x: 14.660920000000011
      y: -6.951919999999998
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
goal reached!
model_state:
  model_name: "goal"
  pose:
    position:
      x: 6.330960000000012
      y: -2.5723399999999934
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
lidar collision
model_state:
  model_name: "goal"
  pose:
    position:
      x: 14.660920000000011
      y: -6.951919999999998
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
Traceback (most recent call last):
  File "cpo_discrete.py", line 456, in <module>
    log_infos = update(data=batch)
  File "cpo_discrete.py", line 246, in update
    old_probs = ac_.pi(o['flat'], encoded_o).detach().clone() + EPS
  File "/home/brain5/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brain5/catkin_ws/src/social_navigation/scripts/model_discrete.py", line 105, in forward
    x = torch.cat([flat, encoded], axis=1)
TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray