
{'exp_name': 'pedsim_cpo', 'exp_epi_len': 200, 'pi_hidden_layers': [128, 128], 'pi_options': ['default', 'leaky-relu', 'default'], 'replay_size': 10000, 'gamma': 0.99, 'lambda': 0.97, 'polyak': 0.995, 'alpha': 0.002, 'learning_rate': 0.0001, 'epochs': 1000, 'steps_per_epoch': 100, 'batch_size': 256, 'n_log_epi': 10, 'start_steps': 100, 'update_after': 100, 'update_every': 20, 'save_interval': 10, 'plot_rendering': True, 'seed': 1}
/home/brain5/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
model_state:
  model_name: "goal"
  pose:
    position:
      x: -26.789359999999995
      y: -7.304300000000001
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
model_state:
  model_name: "goal"
  pose:
    position:
      x: 29.12612000000002
      y: 2.7133600000000015
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
lidar collision
model_state:
  model_name: "goal"
  pose:
    position:
      x: -27.138519999999993
      y: 0.2970399999999991
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
lidar collision
model_state:
  model_name: "goal"
  pose:
    position:
      x: -20.903519999999993
      y: -7.505659999999995
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
Traceback (most recent call last):
  File "cpo_discrete.py", line 456, in <module>
    log_infos = update(data=batch)
  File "cpo_discrete.py", line 233, in update
    gaes_tensor, targets_tensor = getGaesTargets(rewards_tensor, values_tensor, dones_tensor, timeout_tensor, next_values_tensor)
  File "cpo_discrete.py", line 112, in getGaesTargets
    deltas = rewards + (1.0 - dones) * gamma_ * next_values - values
RuntimeError: The size of tensor a (10000) must match the size of tensor b (15) at non-singleton dimension 1